<?php
/**
 * This file is automatically generated and maintained by the
 * QCubed framework. Please do not modify.
 */

//// BEGIN QEmailTextBox
QApplicationBase::$ClassFile['qemailtextbox'] = __PLUGINS__ . '/QEmailTextBox/includes/QEmailTextBox.class.php';
//// END QEmailTextBox

?>